---
# tasks file for prometheus_stack
- name: Create monitoring namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ prometheus_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add prometheus-community Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    binary_path: "{{ helm_binary_path }}"

- name: Copy Prometheus Helm values to bastion
  ansible.builtin.copy:
    src: values.yaml
    dest: /tmp/kube-prometheus-stack-values.yaml
    mode: '0644'

- name: Install/upgrade kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_chart_version }}"
    release_namespace: "{{ prometheus_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
    binary_path: "{{ helm_binary_path }}"
    values_files:
      - /tmp/kube-prometheus-stack-values.yaml
    wait: true
