[bastion]
bastion ansible_host=63.181.38.4 ansible_user=ec2-user

[eks_workers]
worker-1 ansible_host=10.0.2.218 ansible_user=ec2-user
worker-2 ansible_host=10.0.3.135 ansible_user=ec2-user
worker-3 ansible_host=10.0.1.18 ansible_user=ec2-user


